{"name": "test_auditTrailUnitEdit", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'count' referenced before assignment", "trace": "def test_auditTrailUnitEdit():\n>       TestCoverageUnit.auditTrailUnitEdit(driver, oldName, oldDescription, newName, newDescription, \"oldDefaultStatus\")\n\nTestCaseUnit.py:58: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nTestCoverage\\TestCoverageUnit.py:1024: in auditTrailUnitEdit\n    beforeCount=TestCoverageAudittrail.auditTrailRecordCount(driver)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"641ed8a5d34bee30fa44fe59fef88f89\")>\n\n    def auditTrailRecordCount(driver):\n    \n        ScreenNavigate.auditTrailPreCondition(driver)\n    \n        try:\n            countText= driver.find_element(By.XPATH,\"(//*[@class='k-pager-info k-label'])[2]\").text\n    \n            individualText = countText.split(' ')\n    \n            count = individualText[4]\n    \n            logger.info(\"The count is fetched, it shows {} record in the grid\".format(count))\n    \n            count = int(count)\n    \n        except:\n    \n            try:\n                time.sleep(3)\n    \n                countText = driver.find_element(By.XPATH, \"(//*[@class='k-pager-info k-label'])[2]\").text\n    \n                individualText = countText.split(' ')\n    \n                count = individualText[4]\n    \n                logger.info(\"The count is fetched, it shows {} record in the grid\".format(count))\n    \n                count = int(count)\n    \n            except:\n    \n                logger.error(\"Unable to get the count in the Audit trail screen\")\n    \n    \n        ScreenNavigate.auditTrailPostCondition(driver)\n    \n>       return count\nE       UnboundLocalError: local variable 'count' referenced before assignment\n\nTestCoverage\\TestCoverageAudittrail.py:52: UnboundLocalError"}, "attachments": [{"name": "log", "source": "4f7f27ee-a572-436a-9f0d-45921f12ddb4-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "a0c588e5-1899-4e62-bed0-bf26fc637f31-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "5679e040-be40-4f5c-afd4-8dcdc8286875-attachment.txt", "type": "text/plain"}], "start": 1650649751445, "stop": 1650649876822, "uuid": "7fa5ca7f-3baf-44c5-bb3c-ef4f52b604d2", "historyId": "80fd0a984e49269eaeb4772e52335000", "testCaseId": "9e302eac8fd5623c47acee8e52396c61", "fullName": "TestCaseUnit#test_auditTrailUnitEdit", "labels": [{"name": "suite", "value": "TestCaseUnit"}, {"name": "host", "value": "AGL78"}, {"name": "thread", "value": "31084-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCaseUnit"}]}