{"name": "test_auditTrailUnitEdit", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'count' referenced before assignment", "trace": "def test_auditTrailUnitEdit():\n>       TestCoverageUnit.auditTrailUnitEdit(driver, oldName, oldDescription, newName, newDescription, \"oldDefaultStatus\")\n\nTestCaseUnit.py:59: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nTestCoverage\\TestCoverageUnit.py:1040: in auditTrailUnitEdit\n    afterCount = TestCoverageAudittrail.auditTrailRecordCount(driver)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"953d5e904b20f3eff9ee034e807ebc39\")>\n\n    def auditTrailRecordCount(driver):\n    \n        ScreenNavigate.auditTrailPreCondition(driver)\n    \n        try:\n            countText= driver.find_element(By.XPATH,\"(//*[@class='k-pager-info k-label'])[2]\").text\n    \n            individualText = countText.split(' ')\n    \n            count = individualText[4]\n    \n            logger.info(\"The count is fetched, it shows {} record in the grid\".format(count))\n    \n            count = int(count)\n    \n        except:\n    \n            try:\n                time.sleep(3)\n    \n                countText = driver.find_element(By.XPATH, \"(//*[@class='k-pager-info k-label'])[2]\").text\n    \n                individualText = countText.split(' ')\n    \n                count = individualText[4]\n    \n                logger.info(\"The count is fetched, it shows {} record in the grid\".format(count))\n    \n                count = int(count)\n    \n            except:\n    \n                logger.error(\"Unable to get the count in the Audit trail screen\")\n    \n    \n        ScreenNavigate.auditTrailPostCondition(driver)\n    \n>       return count\nE       UnboundLocalError: local variable 'count' referenced before assignment\n\nTestCoverage\\TestCoverageAudittrail.py:52: UnboundLocalError"}, "attachments": [{"name": "log", "source": "26c20926-3ce9-40de-a302-202a2ccc5b94-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "eddd72e5-0dd7-4cc7-a056-1d801acab662-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "e779b383-3768-4b7c-8117-400b38c5ff14-attachment.txt", "type": "text/plain"}], "start": 1650613213423, "stop": 1650613241427, "uuid": "8024f4b1-9bff-4a34-9246-ababc254eaef", "historyId": "80fd0a984e49269eaeb4772e52335000", "testCaseId": "9e302eac8fd5623c47acee8e52396c61", "fullName": "TestCaseUnit#test_auditTrailUnitEdit", "labels": [{"name": "suite", "value": "TestCaseUnit"}, {"name": "host", "value": "AGL78"}, {"name": "thread", "value": "32028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCaseUnit"}]}