{"name": "test_duplicateEntry", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "def test_duplicateEntry():\n>       TestCoverageUnit.unitDuplicate(driver)\n\nTestCaseUnit.py:66: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nTestCoverage\\TestCoverageUnit.py:1775: in unitDuplicate\n    unitAdd(driver,unique,\"d\",\"yes\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"14281613520226a3eaa93ff20ae5d299\")>, name = 'unique', description = 'd'\ndefaultStatus = 'yes'\n\n    def unitAdd(driver,name,description,defaultStatus):\n    \n        ScreenNavigate.unit(driver,\"add\")\n    \n        countListbefore=driver.find_element(By.XPATH,baseMaster.get(\"UnitOfMeasurement\", \"unitCount\")).text\n    \n        countLIST=countListbefore.split(' ')\n    \n>       beforeCount=countLIST[4]\nE       IndexError: list index out of range\n\nTestCoverage\\TestCoverageUnit.py:39: IndexError"}, "attachments": [{"name": "log", "source": "bcbb2867-8bea-4e63-ae7f-767f45e150b4-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "def1e18a-90d3-4bc8-9925-3c345e76ddd3-attachment.txt", "type": "text/plain"}], "start": 1650618026040, "stop": 1650618041561, "uuid": "7a27f24e-d55b-4be1-a802-80dbecbed7cf", "historyId": "e4d6f4258175678babcd45f5151dc307", "testCaseId": "2709ad4565ca74b7309dff1955d95abb", "fullName": "TestCaseUnit#test_duplicateEntry", "labels": [{"name": "suite", "value": "TestCaseUnit"}, {"name": "host", "value": "AGL78"}, {"name": "thread", "value": "19412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCaseUnit"}]}