{"name": "test_auditTrailUnitDelete", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'count' referenced before assignment", "trace": "def test_auditTrailUnitDelete():\n>       TestCoverageUnit.auditTrailUnitDelete(driver, oldName, oldDescription, \"No\")\n\nTestCaseUnit.py:62: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nTestCoverage\\TestCoverageUnit.py:1386: in auditTrailUnitDelete\n    beforeCount=TestCoverageAudittrail.auditTrailRecordCount(driver)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f63f478b1239c4c359646510d252dfff\")>\n\n    def auditTrailRecordCount(driver):\n    \n        ScreenNavigate.auditTrailPreCondition(driver)\n    \n        try:\n            countText= driver.find_element(By.XPATH,\"(//*[@class='k-pager-info k-label'])[2]\").text\n    \n            individualText = countText.split(' ')\n    \n            count = individualText[4]\n    \n            logger.info(\"The count is fetched, it shows {} record in the grid\".format(count))\n    \n            count = int(count)\n    \n        except:\n    \n            try:\n                time.sleep(3)\n    \n                countText = driver.find_element(By.XPATH, \"(//*[@class='k-pager-info k-label'])[2]\").text\n    \n                individualText = countText.split(' ')\n    \n                count = individualText[4]\n    \n                logger.info(\"The count is fetched, it shows {} record in the grid\".format(count))\n    \n                count = int(count)\n    \n            except:\n    \n                logger.error(\"Unable to get the count in the Audit trail screen\")\n    \n    \n        ScreenNavigate.auditTrailPostCondition(driver)\n    \n>       return count\nE       UnboundLocalError: local variable 'count' referenced before assignment\n\nTestCoverage\\TestCoverageAudittrail.py:52: UnboundLocalError"}, "attachments": [{"name": "log", "source": "74ec3565-cca2-4394-a5f9-ff18301e47fe-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ce260d56-bd1e-4197-b40d-9b1665917a03-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "ee1bfd5e-1fed-416e-9a27-c6331141a673-attachment.txt", "type": "text/plain"}], "start": 1650621243776, "stop": 1650621321938, "uuid": "88ffb3fc-df5f-4d65-b186-a8eb3a0a1f26", "historyId": "f4694be4b7ad7e5774e96636685096d6", "testCaseId": "a4cb98532f7d308f67e61ad358d5696e", "fullName": "TestCaseUnit#test_auditTrailUnitDelete", "labels": [{"name": "suite", "value": "TestCaseUnit"}, {"name": "host", "value": "AGL78"}, {"name": "thread", "value": "21384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCaseUnit"}]}